# Generated by Django 4.1.2 on 2023-01-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryfiles",
            name="lsa_matrix",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="repositoryfiles",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
