# Generated by Django 4.1.2 on 2023-01-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis_app", "0002_repositoryfiles_lsa_matrix_repositoryfiles_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repositoryfiles",
            name="text",
        ),
        migrations.AddField(
            model_name="repositoryfiles",
            name="text_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
